language: ruby
rvm:
  - 2.0
  - 2.1
  - 2.2
  - rbx-2
  - jruby
  - ruby-head
  - jruby-head
before_install: gem install bundler -v 1.10.6
script:
  - bundle exec rspec
  - bundle exec rubocop
matrix:
  allow_failures:
    - rvm: ruby-head
    - rvm: jruby-head
